---
version: "3"

services:
  webserver:
    build:
      context: web
    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.backend: webserver
      traefik.frontend.rule: "PathPrefix:/"
    networks:
      backend:

networks:
  backend:
    external: true
