---
version: "3"

services:
  webserver:
    build:
      context: web
    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.backend: webserver
      traefik.frontend.rule: "PathPrefix:/"

  frontend:
    image: traefik
    command:
      - --api
      - --docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
