---
version: "3"

services:
  frontend:
    image: traefik
    command:
      - --api
      - --docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "80:80"
      - "127.0.0.1:8080:8080"
    networks:
      backend:

networks:
  backend:
    external: true
